{
 "title": "K8S Monitoring - Pods",
 "description": "Kubernetes Pods Resource",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "POD RESOURCE INFORMATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\", namespace=~\"$namespace\"}[$__rate_interval])) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HPA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{namespace=\"$namespace\"}",
     "legendFormat": "Min Replicas - {{horizontalpodautoscaler}}"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{namespace=\"$namespace\"}",
     "legendFormat": "Max Replicas - {{horizontalpodautoscaler}}"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=\"$namespace\"}",
     "legendFormat": "Current Replicas - {{horizontalpodautoscaler}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current POD Resource Request and Limit",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container!=\"\", namespace=\"$namespace\"}[5m])) by (namespace, pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"\", namespace!=\"\", namespace=\"$namespace\"}) by (namespace, pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}